import { createHash } from "node:crypto";
import { GMAIL_MINIMUM_SCOPES, type GmailProfile, type GmailTokenSet } from "@/connectors/gmail-contracts";

export class GmailApiError extends Error {
  constructor(readonly code: string, message: string, readonly status = 502) { super(message); this.name = "GmailApiError"; }
}

type Fetcher = typeof fetch;
function oauthBody(value: Record<string, string>) { return new URLSearchParams(value).toString(); }
async function json(response: Response) { const value: unknown = await response.json().catch(() => null); if (!response.ok) throw new GmailApiError(response.status === 401 ? "GMAIL_REAUTH_REQUIRED" : "GMAIL_PROVIDER_ERROR", "Gmail provider request failed.", response.status); return value; }
function record(value: unknown): value is Record<string, unknown> { return Boolean(value && typeof value === "object" && !Array.isArray(value)); }
function scopes(value: unknown, fallback: readonly string[]) { const result = typeof value === "string" ? value.split(/\s+/u).filter(Boolean) : [...fallback]; if (!GMAIL_MINIMUM_SCOPES.every((scope) => result.includes(scope)) || result.some((scope) => !GMAIL_MINIMUM_SCOPES.includes(scope))) throw new GmailApiError("GMAIL_SCOPE_MISMATCH", "Google granted scopes outside the configured minimum.", 403); return [...new Set(result)].sort(); }
function tokenSet(value: unknown, refreshToken: string | null, fallbackScopes: readonly string[], now: number): GmailTokenSet {
  if (!record(value) || typeof value.access_token !== "string" || value.access_token.length < 10 || typeof value.expires_in !== "number" || value.expires_in < 60 ||
      !(typeof value.refresh_token === "string" && value.refresh_token.length >= 10 || refreshToken)) throw new GmailApiError("GMAIL_TOKEN_RESPONSE_INVALID", "Google token response is incomplete.");
  return { accessToken: value.access_token, refreshToken: typeof value.refresh_token === "string" ? value.refresh_token : refreshToken!, expiresAt: new Date(now + value.expires_in * 1_000).toISOString(), scopes: scopes(value.scope, fallbackScopes), tokenType: "Bearer" };
}

export function gmailPkceChallenge(codeVerifier: string) { return createHash("sha256").update(codeVerifier).digest("base64url"); }
export function gmailAuthorizationUrl(input: { clientId: string; redirectUri: string; state: string; codeVerifier: string }) {
  const url = new URL("https://accounts.google.com/o/oauth2/v2/auth");
  url.search = new URLSearchParams({ client_id: input.clientId, redirect_uri: input.redirectUri, response_type: "code", scope: GMAIL_MINIMUM_SCOPES.join(" "), access_type: "offline", prompt: "consent", include_granted_scopes: "false", state: input.state, code_challenge: gmailPkceChallenge(input.codeVerifier), code_challenge_method: "S256" }).toString();
  return url.toString();
}
export async function exchangeGmailCode(fetcher: Fetcher, input: { clientId: string; clientSecret: string; redirectUri: string; code: string; codeVerifier: string }, now = Date.now()) {
  return tokenSet(await json(await fetcher("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: oauthBody({ client_id: input.clientId, client_secret: input.clientSecret, redirect_uri: input.redirectUri, grant_type: "authorization_code", code: input.code, code_verifier: input.codeVerifier }) })), null, GMAIL_MINIMUM_SCOPES, now);
}
export async function refreshGmailToken(fetcher: Fetcher, input: { clientId: string; clientSecret: string; token: GmailTokenSet }, now = Date.now()) {
  return tokenSet(await json(await fetcher("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: oauthBody({ client_id: input.clientId, client_secret: input.clientSecret, refresh_token: input.token.refreshToken, grant_type: "refresh_token" }) })), input.token.refreshToken, input.token.scopes, now);
}
export async function revokeGmailToken(fetcher: Fetcher, token: string) { const response = await fetcher("https://oauth2.googleapis.com/revoke", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: oauthBody({ token }) }); if (!response.ok) throw new GmailApiError("GMAIL_PROVIDER_REVOKE_FAILED", "Google did not confirm token revocation.", response.status); }
async function gmailJson(fetcher: Fetcher, accessToken: string, url: string) { return json(await fetcher(url, { headers: { Authorization: `Bearer ${accessToken}`, Accept: "application/json" } })); }
export async function readGmailProfile(fetcher: Fetcher, accessToken: string): Promise<GmailProfile> { const value = await gmailJson(fetcher, accessToken, "https://gmail.googleapis.com/gmail/v1/users/me/profile"); if (!record(value) || typeof value.emailAddress !== "string" || typeof value.messagesTotal !== "number" || typeof value.threadsTotal !== "number" || typeof value.historyId !== "string") throw new GmailApiError("GMAIL_PROFILE_INVALID", "Gmail profile readback is invalid."); return { emailAddress: value.emailAddress, messagesTotal: value.messagesTotal, threadsTotal: value.threadsTotal, historyId: value.historyId }; }
export async function searchGmail(fetcher: Fetcher, accessToken: string, query: string, maxResults: number) { const url = new URL("https://gmail.googleapis.com/gmail/v1/users/me/messages"); url.searchParams.set("q", query); url.searchParams.set("maxResults", String(Math.min(20, Math.max(1, maxResults)))); const value = await gmailJson(fetcher, accessToken, url.toString()); if (!record(value) || !(value.messages === undefined || Array.isArray(value.messages))) throw new GmailApiError("GMAIL_SEARCH_INVALID", "Gmail search response is invalid."); return { messages: (value.messages ?? []).flatMap((item) => record(item) && typeof item.id === "string" && typeof item.threadId === "string" ? [{ id: item.id, threadId: item.threadId }] : []), resultSizeEstimate: typeof value.resultSizeEstimate === "number" ? value.resultSizeEstimate : 0 }; }
function decodeBody(value: unknown) { if (typeof value !== "string" || value.length > 1_500_000) return null; try { return Buffer.from(value, "base64url").toString("utf8").slice(0, 50_000); } catch { return null; } }
export async function readGmailMessage(fetcher: Fetcher, accessToken: string, messageId: string) { if (!/^[A-Za-z0-9_-]{4,200}$/u.test(messageId)) throw new GmailApiError("GMAIL_MESSAGE_ID_INVALID", "Gmail message id is invalid.", 400); const value = await gmailJson(fetcher, accessToken, `https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(messageId)}?format=full`); if (!record(value) || !record(value.payload) || !Array.isArray(value.payload.headers)) throw new GmailApiError("GMAIL_MESSAGE_INVALID", "Gmail message response is invalid."); const headers = Object.fromEntries(value.payload.headers.flatMap((item) => record(item) && typeof item.name === "string" && typeof item.value === "string" && ["from", "to", "cc", "subject", "date"].includes(item.name.toLowerCase()) ? [[item.name.toLowerCase(), item.value.slice(0, 2_000)]] : [])); const parts = Array.isArray(value.payload.parts) ? value.payload.parts : []; const textPart = parts.find((item) => record(item) && item.mimeType === "text/plain" && record(item.body)); const body = decodeBody(textPart && record(textPart.body) ? textPart.body.data : record(value.payload.body) ? value.payload.body.data : null); return { id: typeof value.id === "string" ? value.id : messageId, threadId: typeof value.threadId === "string" ? value.threadId : null, labelIds: Array.isArray(value.labelIds) ? value.labelIds.filter((item): item is string => typeof item === "string").slice(0, 50) : [], headers, snippet: typeof value.snippet === "string" ? value.snippet.slice(0, 4_000) : "", body }; }

