import { afterEach, expect, it, vi } from "vitest";
import { mkdtemp, mkdir, rm } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { tmpdir } from "node:os";
import path from "node:path";
import type { InstallationConfig } from "@/config/installation-schema";
import type { ResolvedPermissions } from "@/permissions";
import { FileWorkbenchStore } from "./filesystem-store";
import { requestsProjectPreferences, saveProjectPreferences } from "./project-preferences";
vi.mock("server-only", () => ({}));
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))); });
it.each(["quiero que me lo actualices en el proyecto para futuros chats", "tenla en cuenta en el proyecto", "Recorda aquests criteris del projecte"])("recognizes explicit project persistence: %s", message => expect(requestsProjectPreferences(message)).toBe(true));
it.each(["Revisa estas facturas", "No guardes esto en el proyecto", "No quiero que actualices el proyecto"])("rejects non-authorized persistence: %s", message => expect(requestsProjectPreferences(message)).toBe(false));
it("persists verified criteria for a fresh chat, rejects stale edits and never writes another owner's project", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "project-preferences-")); roots.push(root);
  const userId = randomUUID(), usersRoot = path.join(root, "users"); await mkdir(path.join(usersRoot, userId), { recursive: true, mode: 0o700 });
  const config = { installationId: "test", paths: { dataRoot: root, usersRoot } } as InstallationConfig;
  const ws = FileWorkbenchStore.fromInstallation(config), project = await ws.createProject(userId, "Invoices"), thread = await ws.createThread(userId, project.id, "Review");
  const permissions = { installationId: "test", userId, projectId: project.id, rules: [{ ruleId: "tools.execute", action: "execute", effect: "allow" }] } as unknown as ResolvedPermissions;
  const input = { config, userId, ownerUserId: userId, projectId: project.id, threadId: thread.id, message: "Actualiza estos criterios en el proyecto para futuros chats", expectedNotes: "", notes: "Ignorar diferencias menores de 0,05 €.\n\nTabla de cinco columnas.\n- Factura y albarán\n- Producto", permissions };
  const receipt = await saveProjectPreferences(input);
  expect(receipt).toMatchObject({ status: "saved", notes: input.notes });
  expect(await saveProjectPreferences(input)).toMatchObject({ sha256: receipt.sha256 });
  const next = await ws.createThread(userId, project.id, "Next review");
  expect((await ws.getThreadRuntimeContext(userId, next.id)).projectMemory).toBe(input.notes);
  await expect(saveProjectPreferences({ ...input, expectedNotes: input.notes, notes: "Criterios con un control oculto\0" })).rejects.toThrow(/válidos/);
  await expect(saveProjectPreferences({ ...input, notes: "Una edición obsoleta que pierde la corrección." })).rejects.toThrow(/cambiado/);
  await expect(saveProjectPreferences({ ...input, message: "Revisa las facturas" })).rejects.toThrow(/explícitamente/);
  await expect(saveProjectPreferences({ ...input, ownerUserId: randomUUID() })).rejects.toThrow(/autorizar/);
  await expect(saveProjectPreferences({ ...input, permissions: { ...permissions, rules: [...permissions.rules, { ...permissions.rules[0], effect: "deny" }] } })).rejects.toThrow(/autorizar/);
});
