import { afterEach, expect, it, vi } from "vitest";
import { mkdtemp, mkdir, rm } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { tmpdir } from "node:os";
import path from "node:path";
import { rememberProjectSource, requestsFileRetention } from "./remember-project-source";
import { FileWorkbenchStore } from "@/workbench/filesystem-store";
import { FileDocumentStagingStore } from "./staging-store";
import { ResourceLockManager } from "@/storage/resource-lock";
import { validateUploadedDocument } from "./upload-validation";
import type { InstallationConfig } from "@/config/installation-schema";
import type { ResolvedPermissions } from "@/permissions";
vi.mock("server-only", () => ({}));
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))); });
it.each(["Recorda aquest arxiu", "Recuerda este archivo para otras conversaciones", "Please remember this file"])("recognizes an explicit request: %s", message => expect(requestsFileRetention(message)).toBe(true));
it.each(["No recordis aquest arxiu", "Don't remember this file", "Revisa este archivo"])("does not treat a non-retention request as authorization: %s", message => expect(requestsFileRetention(message)).toBe(false));
it("remembers the original from an earlier message once and binds it to this project", async () => {
 const root=await mkdtemp(path.join(tmpdir(),"remember-source-")); roots.push(root);
 const userId=randomUUID(), usersRoot=path.join(root,"users"); await mkdir(path.join(usersRoot,userId),{recursive:true,mode:0o700});
 const config={installationId:"test",paths:{dataRoot:root,usersRoot}} as InstallationConfig;
 const ws=FileWorkbenchStore.fromInstallation(config), project=await ws.createProject(userId,"References"), thread=await ws.createThread(userId,project.id,"Invoices");
 const staging=new FileDocumentStagingStore(path.join(usersRoot,userId,"staging"),new ResourceLockManager({rootDirectory:path.join(root,"locks")}));
 const data=Buffer.from("ORIGINAL PRICE 79.42"), uploadId=randomUUID();
 const validated=validateUploadedDocument({fileName:"reference.txt",declaredMimeType:"text/plain",data});
 const document=await staging.stage({threadId:thread.id,uploadId,validated,data});
 const base={createdAt:new Date().toISOString(),status:"complete" as const,activity:[],plan:[],approvals:[],diff:"",artifacts:[]};
 await ws.beginThreadTurn(userId,thread.id,{...base,id:randomUUID(),role:"user",content:"Review",attachments:[{id:uploadId,name:document.fileName,size:document.size,mimeType:document.mediaType}]},{...base,id:randomUUID(),role:"assistant",content:"Done",attachments:[]});
 const permissions={installationId:"test",userId,projectId:project.id,rules:[{ruleId:"documents.read",action:"consult",effect:"allow"}]} as unknown as ResolvedPermissions;
 const input={config,userId,ownerUserId:userId,projectId:project.id,threadId:thread.id,message:"Recorda aquest arxiu",fileName:document.fileName,permissions,currentDocuments:[]};
 expect(await rememberProjectSource(input)).toMatchObject({status:"saved",sha256:document.sha256,sourceId:uploadId});
 expect(await rememberProjectSource(input)).toMatchObject({status:"saved",sourceId:uploadId});
 expect((await ws.getProject(userId,project.id)).sources).toHaveLength(1);
 const next=await ws.createThread(userId,project.id,"Next conversation");
 expect((await ws.getThreadRuntimeContext(userId,next.id)).projectSources).toEqual([expect.objectContaining({id:uploadId,status:"ready",excerpt:null})]);
 await expect(rememberProjectSource({...input,message:"No recordis aquest arxiu"})).rejects.toThrow(/explícitamente/);
 await expect(rememberProjectSource({...input,fileName:"foreign.txt"})).rejects.toThrow(/único/);
 await expect(rememberProjectSource({...input,projectId:randomUUID()})).rejects.toThrow(/autorizar/);
});
